# Generated by Django 3.0 on 2019-04-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='puntuacion',
            field=models.DecimalField(decimal_places=2, max_digits=1000),
        ),
    ]
